#' Synthetic gastric-symptom dataset
#'
#' A fully simulated dataset (not patient data) mimicking the structure of a
#' gastric-symptom study: demographics, gastric metrics, symptom sub-scales, and
#' summary scores for 100 imaginary subjects, one row per subject. Loadings are
#' deliberately moderate and uneven, so only a realistic subset of correlations
#' is significant. Generated by `data-raw/make_example_data.R`.
#'
#' Bundled with the package (`LazyData: true`), so it is available directly as
#' `gastro_symptoms` as soon as you `library(circlecorR)` -- no `data()` call
#' needed. Pass it straight to [corr_wheel()]; see `vignette("circlecorR")` for
#' a worked example.
#'
#' @format A data frame with 100 rows and 16 variables:
#' \describe{
#'   \item{Age, BMI}{Demographics.}
#'   \item{Amplitude, Fed-Fasted AR, Frequency, GA-RI}{Simulated gastric metrics.}
#'   \item{Nausea, Early satiety, Bloating, Upper GI pain, Lower GI pain, Heartburn}{Symptom sub-scale scores.}
#'   \item{GCSI, PAGI-SYM, PAGI-QoL, EQ-5D}{Summary symptom and quality-of-life scores.}
#' }
#' @seealso [corr_wheel()], [compute_correlations()]
"gastro_symptoms"
