#' Synthetic gastric-symptom dataset
#'
#' A fully simulated dataset (not patient data) mimicking the structure of a
#' gastric-symptom study: demographics, gastric metrics, symptom sub-scales, and
#' summary scores for 100 imaginary subjects. Loadings are deliberately
#' moderate and uneven, so only a realistic subset of correlations is
#' significant. Generated by `data-raw/make_example_data.R`.
#'
#' @format A data frame with 100 rows and 16 variables:
#' \describe{
#'   \item{Age, BMI}{Demographics.}
#'   \item{Amplitude, Fed-Fasted AR, Frequency, GA-RI}{Simulated gastric metrics.}
#'   \item{Nausea, Early satiety, Bloating, Upper GI pain, Lower GI pain, Heartburn}{Symptom sub-scale scores.}
#'   \item{GCSI, PAGI-SYM, PAGI-QoL, EQ-5D}{Summary symptom and quality-of-life scores.}
#' }
#' @seealso [gastro_cor]
"gastro_symptoms"

#' Correlation matrices for the synthetic gastric-symptom dataset
#'
#' A `"circlecor"` object (Pearson, Hochberg-adjusted) computed from
#' [gastro_symptoms] with [compute_correlations()]. Ready to pass to
#' [corr_wheel()].
#'
#' @format A list of class `"circlecor"` with elements `r` (16x16 correlation
#'   matrix) and `p` (16x16 p-value matrix).
#' @seealso [gastro_symptoms], [corr_wheel()]
"gastro_cor"
